#Movies
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('A','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 10.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('B','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 9.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('C','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 8.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('D','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 7.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('E','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 6.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('F','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 5.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('G','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 4.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('H','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 3.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('I','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 2.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('J','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 1.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('K','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 10.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('L','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 9.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('M','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 8.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('N','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 7.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('O','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 6.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('P','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 5.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Q','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 4.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('R','Genre1','thumbnail.png','video.mp4','Movie1 Desc..',3.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('S','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 2.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('T','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 1.0);
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('U','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', 10.0);