#Movies
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie1','Genre1','thumbnail.png','video.mp4','Movie1 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie2','Genre1','thumbnail.png','video.mp4','Movie2 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie3','Genre1','thumbnail.png','video.mp4','Movie3 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie4','Genre3','thumbnail.png','video.mp4','Movie4 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie5','Genre3','thumbnail.png','video.mp4','Movie5 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie6','Genre4','thumbnail.png','video.mp4','Movie6 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie7','Genre2','thumbnail.png','video.mp4','Movie7 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie8','Genre3','thumbnail.png','video.mp4','Movie8 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie9','Genre2','thumbnail.png','video.mp4','Movie9 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie10','Genre2','thumbnail.png','video.mp4','Movie10 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie11','Genre1','thumbnail.png','video.mp4','Movie11 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie12','Genre2','thumbnail.png','video.mp4','Movie12 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie13','Genre3','thumbnail.png','video.mp4','Movie13 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie14','Genre4','thumbnail.png','video.mp4','Movie14 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie15','Genre2','thumbnail.png','video.mp4','Movie15 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie16','Genre4','thumbnail.png','video.mp4','Movie16 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie17','Genre2','thumbnail.png','video.mp4','Movie17 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie18','Genre2','thumbnail.png','video.mp4','Movie18 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie19','Genre3','thumbnail.png','video.mp4','Movie19 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie20','Genre2','thumbnail.png','video.mp4','Movie20 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie21','Genre2','thumbnail.png','video.mp4','Movie21 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie22','Genre3','thumbnail.png','video.mp4','Movie22 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie23','Genre2','thumbnail.png','video.mp4','Movie23 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');
INSERT INTO `mediatime-db`.Movies(`Name`,`Genre`,`Thumbnail`,`Video`,`Desc`,`Rating`) 
VALUES('Movie24','Genre4','thumbnail.png','video.mp4','Movie24 Desc..', '9.1');


